services:
  - type: web
    name: dbmg-website
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dbmg-db
          property: connectionString

databases:
  - name: dbmg-db
    plan: free





